backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/images
public_folder: /images

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/pages/home.yml'
        fields:
          - { label: Document Title (SEO), name: docTitle, widget: string }
          - label: Section 1
            name: section1
            widget: object
            fields:
              - { label: Title1, name: title1, widget: string }
              - { label: Title2, name: title2, widget: string }
              - { label: Title3, name: title3, widget: string }
              - { label: Description, name: description, widget: string }
              - { label: Description_2, name: description2, widget: string }
              - { label: Description_3, name: description3, widget: string }
          - label: Section 2
            name: section2
            widget: object
            fields:
              - { label: label, name: label, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: string }
              - { label: box1Label, name: box1Label, widget: string }
              - { label: box1Text, name: box1Text, widget: string }
              - { label: box2Label, name: box2Label, widget: string }
              - { label: box2Text, name: box2Text, widget: string }
          - label: Section 3
            name: section3
            widget: object
            fields:
              - label: title
                name: title
                widget: string
              - label: title2
                name: title2
                widget: string
              - label: labelLeft
                name: labelLeft
                widget: string
              - label: labelLeft2
                name: labelLeft2
                widget: string
              - label: descriptionLeft
                name: descriptionLeft
                widget: string
              - label: labelRight
                name: labelRight
                widget: string
              - label: labelRight2
                name: labelRight2
                widget: string
              - label: descriptionRight
                name: descriptionRight
                widget: string
              - label: cards
                name: cards
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - { label: Card title, name: title, widget: string }
                  - { label: Card text, name: text, widget: string }
                  - {
                      label: Card Image,
                      name: image,
                      widget: image,
                    }
          - label: Section 4
            name: section4
            widget: object
            fields:
              - { label: title, name: title, widget: string }
              - { label: title2, name: title2, widget: string }
              - { label: title3, name: title3, widget: string }
              - { label: description, name: description, widget: string }
          - label: Section 5
            name: section5
            widget: object
            fields:
              - { label: title, name: title, widget: string }
              - label: Carousel Items
                name: carouselItems
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - { label: title, name: title, widget: string }
                  - { label: text, name: text, widget: string }
                  - { label: image, name: image, widget: image }
          - label: Section 6
            name: section6
            widget: object
            fields:
              - label: label
                name: label
                widget: string
              - label: description
                name: description
                widget: string
              - label: reviews
                name: reviews
                widget: list
                summary: '{{fields.name}}'
                fields:
                  - { label: Reviewer Name, name: name, widget: string }
                  - {
                      label: Reviewer Position,
                      name: position,
                      widget: string,
                    }
                  - { label: Review Text, name: text, widget: string }
                  - {
                      label: Review Image,
                      name: image,
                      widget: image,
                    }
              - {
                  label: bannerDescription,
                  name: bannerDescription,
                  widget: string,
                }
              - { label: lowerTitle1, name: lowerTitle1, widget: string }
              - { label: lowerTitle2, name: lowerTitle2, widget: string }
              - { label: lowerTitle3, name: lowerTitle3, widget: string }
              - { label: lowerText, name: lowerText, widget: string }
      - label: 'About Page'
        name: 'about'
        file: 'content/pages/about.yml'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }

  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
