backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/images
public_folder: /images

collections:
  - name: 'components'
    label: 'Components'
    files:
      - label: 'Header'
        name: 'header'
        file: 'content/components/header.yml'
        widget: object
        fields:
          - { label: link1, name: link1, widget: string }
          - { label: link2, name: link2, widget: string }
          - { label: link3, name: link3, widget: string }
          - { label: link4, name: link4, widget: string }
          - { label: link5, name: link5, widget: string }
          - { label: link6, name: link6, widget: string }
          - label: DropdownLinks
            name: dropdownLinks
            widget: object
            fields:
              - { label: link1, name: link1, widget: string }
              - { label: description1, name: description1, widget: string }
              - { label: link2, name: link2, widget: string }
              - { label: description2, name: description2, widget: string }
              - { label: link3, name: link3, widget: string }
              - { label: description3, name: description3, widget: string }
              - { label: link4, name: link4, widget: string }
              - { label: description4, name: description4, widget: string }
              - { label: link5, name: link5, widget: string }
              - { label: description5, name: description5, widget: string }
              - { label: link6, name: link6, widget: string }
              - { label: description6, name: description6, widget: string }
      - label: 'Footer'
        name: 'footer'
        file: 'content/components/footer.yml'
        widget: object
        fields:
          - { label: label1, name: label1, widget: string }
          - { label: phone, name: phone, widget: string }
          - { label: label2, name: label2, widget: string }
          - { label: email, name: email, widget: string }
          - label: 'Products Section'
            name: 'productsSection'
            widget: object
            fields:
              - { label: title, name: title, widget: string }
              - { label: link1, name: link1, widget: string }
              - { label: link2, name: link2, widget: string }
              - { label: link3, name: link3, widget: string }
              - { label: link4, name: link4, widget: string }
              - { label: link5, name: link5, widget: string }
              - { label: link6, name: link6, widget: string }
          - label: 'Resources Section'
            name: 'resourcesSection'
            widget: object
            fields:
              - { label: title, name: title, widget: string }
              - { label: link1, name: link1, widget: string }
              - { label: link2, name: link2, widget: string }
              - { label: link3, name: link3, widget: string }
              - { label: link4, name: link4, widget: string }
              - { label: link5, name: link5, widget: string }
          - label: 'Legal Section'
            name: 'legalSection'
            widget: object
            fields:
              - { label: title, name: title, widget: string }
              - { label: link1, name: link1, widget: string }
              - { label: link2, name: link2, widget: string }
              - { label: link3, name: link3, widget: string }

  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/pages/home.yml'
        fields:
          - { label: Document Title (SEO), name: docTitle, widget: string }
          - label: Section 1
            name: section1
            widget: object
            fields:
              - { label: Title1, name: title1, widget: string }
              - { label: Title2, name: title2, widget: string }
              - { label: Title3, name: title3, widget: string }
              - { label: Description, name: description, widget: string }
              - { label: Description_2, name: description2, widget: string }
              - { label: Description_3, name: description3, widget: string }
          - label: Section 2
            name: section2
            widget: object
            fields:
              - { label: label, name: label, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: string }
              - { label: box1Label, name: box1Label, widget: string }
              - { label: box1Text, name: box1Text, widget: string }
              - { label: box2Label, name: box2Label, widget: string }
              - { label: box2Text, name: box2Text, widget: string }
          - label: Section 3
            name: section3
            widget: object
            fields:
              - label: title
                name: title
                widget: string
              - label: title2
                name: title2
                widget: string
              - label: labelLeft
                name: labelLeft
                widget: string
              - label: labelLeft2
                name: labelLeft2
                widget: string
              - label: descriptionLeft
                name: descriptionLeft
                widget: string
              - label: labelRight
                name: labelRight
                widget: string
              - label: labelRight2
                name: labelRight2
                widget: string
              - label: descriptionRight
                name: descriptionRight
                widget: string
              - label: cards
                name: cards
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - { label: Card title, name: title, widget: string }
                  - { label: Card text, name: text, widget: string }
                  - { label: Card Image, name: image, widget: image }
          - label: Section 4
            name: section4
            widget: object
            fields:
              - { label: title, name: title, widget: string }
              - { label: title2, name: title2, widget: string }
              - { label: title3, name: title3, widget: string }
              - { label: description, name: description, widget: string }
          - label: Section 5
            name: section5
            widget: object
            fields:
              - label: title
                name: title
                widget: string
              - label: Carousel Items
                name: carouselItems
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - { label: title, name: title, widget: string }
                  - { label: text, name: text, widget: string }
                  - { label: image, name: image, widget: image }
          - label: Section 6
            name: section6
            widget: object
            fields:
              - label: label
                name: label
                widget: string
              - label: description
                name: description
                widget: string
              - label: reviews
                name: reviews
                widget: list
                summary: '{{fields.name}}'
                fields:
                  - { label: Reviewer Name, name: name, widget: string }
                  - { label: Reviewer Position, name: position, widget: string }
                  - { label: Review Text, name: text, widget: string }
                  - { label: Review Image, name: image, widget: image }
              - {
                  label: bannerDescription,
                  name: bannerDescription,
                  widget: string,
                  
                }
              - { label: lowerTitle1, name: lowerTitle1, widget: string }
              - { label: lowerTitle2, name: lowerTitle2, widget: string }
              - { label: lowerTitle3, name: lowerTitle3, widget: string }
              - { label: lowerText, name: lowerText, widget: string }
      - label: 'Accept payments account-to-account payment'
        name: 'acceptPaymentsAccountToAccountPayment'
        file: 'content/pages/accept-payments-account-to-account-payment.yml'
        fields:
          - label: Viewport 1
            name: viewport1
            widget: object
            fields:
              - { label: Title1, name: title1, widget: string }
              - { label: Title2, name: title2, widget: string }
              - { label: Description, name: description, widget: string }
              - { label: Description_2, name: description2, widget: string }
          - label: Viewport 2
            name: viewport2
            widget: object
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Description_1, name: description1, widget: string }
              - { label: Description_2, name: description2, widget: string }
              - { label: Description_3, name: description3, widget: string }
              - { label: BoxTitle1, name: boxTitle1, widget: string }
              - { label: BoxListItem1, name: boxListItem1, widget: string }
              - { label: BoxListItem2, name: boxListItem2, widget: string }
              - { label: BoxListItem3, name: boxListItem3, widget: string }
              - { label: BoxListItem4, name: boxListItem4, widget: string }
          - label: Viewport 3
            name: viewport3
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
          - label: Viewport 3 cards
            name: viewport3Cards
            widget: list
            summary: '{{fields.title}}'
            fields:
              - { label: title, name: title, widget: string }
              - { label: text, name: text, widget: string }
              - { label: image, name: image, widget: image }
          - label: Viewport 4
            name: viewport4
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: string }
          - label: Step cards
            name: stepCards
            widget: list
            summary: '{{fields.title}}'
            fields:
              - { label: Label, name: Label, widget: string }
              - { label: Title, name: Title, widget: string }
              - { label: Description, name: Description, widget: string }
          - label: Viewport 5
            name: viewport5
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: string }
          - label: Benefit Cards
            name: benefitCards
            widget: list
            summary: '{{fields.title}}'
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: string }
          - label: Viewport 6
            name: viewport6
            widget: object
            fields:
              - { label: title, name: title, widget: string }
              - label: Carousel Items
                name: carouselItems
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - { label: title, name: title, widget: string }
                  - { label: text, name: text, widget: string }
                  - { label: image, name: image, widget: image }
          - label: Viewport 7
            name: viewport7
            widget: object
            fields:
              - { label: bannerLabel, name: bannerLabel, widget: string }
              - { label: bannerDescription, name: bannerDescription, widget: string }
              - { label: lowerTitle1, name: lowerTitle1, widget: string }
              - { label: lowerTitle2, name: lowerTitle2, widget: string }
              - { label: lowerText, name: lowerText, widget: string }
      - label: 'Accept payments-ecommerce and online payments'
        name: 'AcceptPaymentsEcommerceAndOnlinePayments'
        file: 'content/pages/accept-payments-ecommerce-and-online-payments.yml'
        fields:
          - label: Viewport 1
            name: viewport1
            widget: object
            fields:
              - { label: Title1, name: title1, widget: string }
              - { label: Title2, name: title2, widget: string }
              - { label: Description, name: description, widget: string }
              - { label: Description_2, name: description2, widget: string }
          - label: Benefit Cards 
            name: benefitCards
            widget: list
            summary: '{{fields.title}}'
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: string }
          - label: Viewport 3
            name: viewport3
            widget: object
            fields:
              - { label: Title1, name: title1, widget: string }
              - { label: Title2, name: title2, widget: string }
              - { label: Description, name: Description, widget: string }
          - label: Plugin Cards 
            name: pluginCards
            widget: list
            summary: '{{fields.title}}'
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Image, name: image, widget: string }
          - label: Viewport 4
            name: viewport4
            widget: object
            fields:
              - { label: title, name: title, widget: string }
              - label: Carousel Items
                name: carouselItems
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - { label: title, name: title, widget: string }
                  - { label: text, name: text, widget: string }
                  - { label: image, name: image, widget: image }
          - label: Viewport 5
            name: viewport5
            widget: object
            fields:
              - { label: bannerLabel, name: bannerLabel, widget: string }
              - { label: bannerDescription, name: bannerDescription, widget: string }
              - { label: lowerTitle1, name: lowerTitle1, widget: string }
              - { label: lowerTitle2, name: lowerTitle2, widget: string }
              - { label: lowerText, name: lowerText, widget: string }
      - label: 'Accept payments payment-links'
        name: 'acceptPaymentsPaymentLinks'
        file: 'content/pages/accept-payments-payment-links.yml'
        fields:
          - label: Viewport 1
            name: viewport1
            widget: object
            fields:
              - { label: Title1, name: title1, widget: string }
              - { label: Title2, name: title2, widget: string }
              - { label: Description_1, name: description1, widget: string }
              - { label: Description_2, name: description2, widget: string }
          - label: Viewport 2
            name: viewport2
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: string }
          - label: Link Cards 
            name: linkCards
            widget: list
            summary: '{{fields.title}}'
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Text, name: text, widget: string }
              - { label: Image, name: image, widget: image }
          - label: Viewport 3
            name: viewport3
            widget: object
            fields:
              - { label: title, name: title, widget: string }
              - label: Carousel Items
                name: carouselItems
                widget: list
                summary: '{{fields.title}}'
                fields:
                  - { label: title, name: title, widget: string }
                  - { label: text, name: text, widget: string }
                  - { label: image, name: image, widget: image }
          - label: Viewport 4
            name: viewport4
            widget: object
            fields:
              - { label: bannerLabel, name: bannerLabel, widget: string }
              - { label: bannerDescription, name: bannerDescription, widget: string }
              - { label: lowerTitle1, name: lowerTitle1, widget: string }
              - { label: lowerTitle2, name: lowerTitle2, widget: string }
              - { label: lowerText, name: lowerText, widget: string }
      - label: 'About Page'
        name: 'about'
        file: 'content/pages/about.yml'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }

  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
